src/Entity/UserInvit.php
<?php

namespace App\Entity;

use App\Repository\UserInvitRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UserInvitRepository::class)
 */
class UserInvit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $createdby;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdat;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedat;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="userInvits")
     */
    private $receiverinvit;

    /**
     * @ORM\ManyToOne(targetEntity=Site::class, inversedBy="userInvitsite")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Sites;

    /**
     * @ORM\Column(type="array")
     * @var array
     */
    private $Roles ;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $role;
    public function __construct()
    {
        $this->Roles = array();
    }
   

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedby(): ?string
    {
        return $this->createdby;
    }

    public function setCreatedby(string $createdby): self
    {
        $this->createdby = $createdby;

        return $this;
    }

    public function getCreatedat(): ?\DateTimeInterface
    {
        return $this->createdat;
    }

    public function setCreatedat(\DateTimeInterface $createdat): self
    {
        $this->createdat = $createdat;

        return $this;
    }

    public function getUpdatedat(): ?\DateTimeInterface
    {
        return $this->updatedat;
    }

    public function setUpdatedat(\DateTimeInterface $updatedat): self
    {
        $this->updatedat = $updatedat;

        return $this;
    }

    public function getReceiverinvit(): ?User
    {
        return $this->receiverinvit;
    }

    public function setReceiverinvit(?User $ReceiverInvit): self
    {
        $this->receiverinvit = $ReceiverInvit;

        return $this;
    }
    

    public function getSites(): ?Site
    {
        return $this->Sites;
    }

    public function setSites(?Site $Sites): self
    {
        $this->Sites = $Sites;

        return $this;
    }

    public function getRoles(): ?array
    {
        return $this->Roles;
    }

    public function setRoles(array $Roles): self
    {
        $this->Roles = $Roles;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }
    public function addRole($role)
    {
        $role = strtoupper($role);
     

        if (!in_array($role, $this->Roles, true)) {
            $this->Roles[] = $role;
        }

        return $this;
    }

  
    public function hasRoles($role)
    {
        return in_array(strtoupper($role), $this->getRoles(), true);
    }
}

src/Controller/UserInvitController.php
<?php

namespace App\Controller;

use App\Entity\UserInvit;
use App\Form\UserInviType;
use App\Repository\MotsClesRepository;
use App\Repository\UserInvitRepository;
use Mgilet\NotificationBundle\Manager\NotificationManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * @Route("/cms/invitation_user")
 */
class UserInvitController extends AbstractController
{
    private $manager;

    public function __construct(NotificationManager $manager)
    {
        $this->manager=$manager;
       
    }
    
    /**
     * @Route("/", name="cms_UserInvit_index")
     */
    public function index(UserInvitRepository $ftr): Response
    {
        $em=$this->getDoctrine()->getManager();
        $usersinvit=$ftr->findByCreatedby($this->getUser()->getUserName());
        return $this->render('user_invit/index.html.twig', [
            'list_usersinvit' =>$usersinvit,
        ]);
    }

    /**
     * @Route("/new", name="cms_UserInvit_new", methods={"GET","POST"})
     */
    public function new(Request $request,\Swift_Mailer $mailer,MotsClesRepository $mc,TranslatorInterface $translator): Response
    {
    $Userinvit = new UserInvit();
        $form = $this->createForm(UserInviType::class, $Userinvit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $user = $this->getUser();
           
             $em = $this->getDoctrine()->getManager();
             $Userinvit->setCreatedBy($user->getUsername());
             $date = new \DateTime('now');
             $Userinvit->setCreatedAt($date);
             $Userinvit->setUpdatedAt($date);
             $Userinvit->addRole($Userinvit->getRole());
             $message = (new \Swift_Message())
             ->setFrom($user->getEmail())
             ->setSubject('Invitation To manage Site')
             ->setContentType('text/html')
             ->setTo($Userinvit->getReceiverInvit()->getEmail());
           // ->setBody($_POST['message'])
             
             $img = $message->embed(\Swift_Image::fromPath('images/logo_title.png'));
             if ($Userinvit->getRole()=="ROLE_MODERATOR") {
                        $role="Moderator";
                    }
             elseif($Userinvit->getRole()=="ROLE_EDITOR"){
                    $role="Editor";  
                }
             elseif($Userinvit->getRole()=="ROLE_AUTHOR"){
                    $role="AUthor";                           
                }
                $img = $message->embed(\Swift_Image::fromPath('images/logo_title.png'));
                $img1 = $message->embed(\Swift_Image::fromPath('images/ico-facebook.png'));
                $img2 = $message->embed(\Swift_Image::fromPath('images/ico-twitter.png'));
                $img3 = $message->embed(\Swift_Image::fromPath('images/ico-google-plus.png'));
                $img4 = $message->embed(\Swift_Image::fromPath('images/ico-linkedin.png'));
                $img7 = $message->embed(\Swift_Image::fromPath('images/img-07.jpg'));
                $img8 = $message->embed(\Swift_Image::fromPath('images/img-08.jpg'));
             
                $img9 = $message->embed(\Swift_Image::fromPath('images/img-09.jpg'));
                $img10 = $message->embed(\Swift_Image::fromPath('images/img-10.jpg'));
                $img11 = $message->embed(\Swift_Image::fromPath('images/img-11.jpg'));
                $img12 = $message->embed(\Swift_Image::fromPath('images/img-12.jpg'));
                $messagereturn="Invitation Sent To You BY";

        $messageusers ='You have been invited from  '.$user->getUsername().' to menage a web site  named<b> '. $Userinvit->getSites()->getName() .' </b>With a <b>  '. $role .' </b>Role'; 
            $message->setBody($this->render('Emails/contact.html.twig', ['messagereturn' =>$messagereturn,'messagesusers' =>$messageusers,'img' => $img,'messagesfrom' =>$user->getUsername(),'img1' => $img1,'img2' => $img2,'img3' => $img3,'img4' => $img4,'img7' => $img7,'img8' => $img8,'img9' => $img9,'img10' => $img10,'img11' => $img11,'img12' => $img12]));
        ;
        
        $mailer->send($message);
           $motscle=$mc->findByCreatedby($user->getUsername());
           $array=array();
           $array[]=$Userinvit->getReceiverInvit()->getUsername();

           foreach($motscle as $mt){
               $mt->setUseraccess($array);
           }


            $entityManager->persist($Userinvit);
            $entityManager->flush();
            $message=$translator->trans('New Invitation has been sent to user ');

            $this->get('session')->getFlashBag()->add(
                'userinvit',
                array(
                   
                    'message' => $message
                )
            );
            $notif = $this->manager->createNotification('Invitation !');
            $notif->setMessage('You are invited by '.$this->getUser().'to access site with role'.$role);
            $notif->setLink('https://Youdev-it.com/');
            // or the one-line method :
            // $manager->createNotification('Notification subject', 'Some random text', 'https://google.fr/');
  
            // you can add a notification to a list of entities
            // the third parameter `$flush` allows you to directly flush the entities
            $this->manager->addNotification(array($Userinvit->getReceiverInvit()), $notif, true);

            return $this->redirectToRoute('cms_UserInvit_index');
          
        }

        return $this->render('user_invit/new.html.twig', [
            'Userinvit' => $Userinvit,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/{id}/update", name="cms_UserInvit_update", methods={"GET","POST"})
     */
    public function update(Request $request,UserInvitRepository $ftr,$id,TranslatorInterface $translator): Response
    {
    $Userinvit =$ftr->find($id);
        $form = $this->createForm(UserInviType::class, $Userinvit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $user = $this->getUser();
           
            $em = $this->getDoctrine()->getManager();
          
             $date = new \DateTime('now');
             $Userinvit->addRole($Userinvit->getRole());

            $Userinvit->setUpdatedAt($date);



            $entityManager->persist($Userinvit);
            $entityManager->flush();
            $message=$translator->trans('User Invit informations has been changed successfully ');

            $this->get('session')->getFlashBag()->add(
                'userinvit',
                array(
                   
                    'message' => $message
                )
            );
            return $this->redirectToRoute('cms_UserInvit_index');

        }

        return $this->render('user_invit/update.html.twig', [
            'Userinvit' => $Userinvit,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/{id}/delete", name="cms_UserInvit_delete")
     */
    public function delete($id,UserInvitRepository $ftrrep): Response
    {  $em=$this->getDoctrine()->getManager();
        $userinvit =$ftrrep->find($id); 
        $em->remove($userinvit);
        $em->flush();
        return $this->redirectToRoute('cms_UserInvit_index');
    }

}

templates/user_invit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}User Invitation{% endtrans %}{% endblock %}

{% block stylesheets %}
<meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
	<link rel="icon" href="{{asset('assets/img/icon.ico')}}" type="image/x-icon"/>

	<!-- Fonts and icons -->
	<script src="{{asset('assets/js/plugin/webfont/webfont.min.js')}}"></script>
	<script>
		WebFont.load({
			google: {"families":["Open+Sans:300,400,600,700"]},
			custom: {"families":["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands"], urls: ['{{asset('assets/css/fonts.css')}}']},
			active: function() {
				sessionStorage.fonts = true;
			}
		});
	</script>
    <style>
    #home{
    margin-left: 50px;
    }
    </style>
    
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css">

	<!-- CSS Files -->
	<link rel="stylesheet" href="{{asset('assets/css/bootstrap.min.css')}}">
	<link rel="stylesheet" href="{{asset('assets/css/azzara.min.css')}}">

	<!-- CSS Just for demo purpose, don't include it in your project -->
	<link rel="stylesheet" href="{{asset('assets/css/demo.css')}}">
{% endblock %}
{% block Userprofile %}
						<div class="avatar-sm float-left mr-2">
							<img src="{{asset('assets/img/profile.jpg')}}" alt="..." class="avatar-img rounded-circle">
						</div>
						<div class="info">
							<a data-toggle="collapse" href="#collapseExample" aria-expanded="true">
								<span>
									Hizrian
									<span class="user-level">Administrator</span>
									<span class="caret"></span>
								</span>
							</a>
							<div class="clearfix"></div>

							<div class="collapse in" id="collapseExample">
								<ul class="nav">
									<li>
										<a href="#profile">
											<span class="link-collapse">{% trans %}My Profil {% endtrans %}</span>
										</a>
									</li>
									<li>
										<a href="#edit">
											<span class="link-collapse">{% trans %}Edit Profil {% endtrans %}</span>
										</a>
									</li>
									<li>
										<a href="#settings">
											<span class="link-collapse">{% trans %}Settings{% endtrans %}</span>
										</a>
									</li>
								</ul>
							</div>
						</div>
						
						
{% endblock %}
{% block projests %}
          <li class="nav-item">
							<a  href="{{path('cms_site_list')}}">
								<i class="fas fa-circle-notch"></i>
								<p>{% trans %}Sites{% endtrans %}</p>
								<span class="caret"></span>
							</a>
                                </li>
                            
{% endblock %}

{% block page %}
          <li class="nav-item">

<a href="{{path('cms_page_list')}}">
								<i class="fas fa-copy"></i>
								<p>{% trans %}pages{% endtrans %}</p>
								<span class="caret"></span>
							</a>
                                </li>
{% endblock %}

				{% block FAQ %}
				<li class="nav-item">

				<a href="{{path('cms_faq_list')}}">
				<i class="fas fa-question-circle"></i>
				<p>{% trans %}FAQ{% endtrans %}</p>
				<span class="caret"></span>
				</a>
				</li>
				{% endblock %}
				{% block blocks_site %}
				<li class="nav-item">

				<a data-toggle="collapse" href="#blocks_site">
				<i class="fas fa-layer-group"></i>
				<p>{% trans %}Site Block{% endtrans %}</p>
				<span class="caret"></span>
				</a>
				<div class="collapse" id="blocks_site">
				<ul class="nav nav-collapse">
					<li>
						<a href="{{path('cms_menu_index')}}">
							<span class="sub-item">{% trans %}Menu{% endtrans %}</span>
						</a>
					</li>
					<li>
						<a href="{{path('cms_footer_index')}}">
							<span class="sub-item">{% trans %}footer{% endtrans %}</span>
						</a>
					</li>
		 <li>
						<a href="{{path('cms_service_index')}}">
							<span class="sub-item">{% trans %}Services{% endtrans %}</span>
						</a>
					</li>

				</ul>
			</div>
				</li>
				{% endblock %}
				{% block blocks %}
				<li class="nav-item">

				<a data-toggle="collapse" href="#blocks">
				<i class="fas fa-layer-group"></i>
				<p>{% trans %}Page Block{% endtrans %}</p>
				<span class="caret"></span>
				</a>
				<div class="collapse" id="blocks">
				<ul class="nav nav-collapse">
				
					<li>
						<a href="{{path('cms_gallery_index')}}">
							<span class="sub-item">{% trans %}gallery{% endtrans %}</span>
						</a>
					</li>
			
					<li>
						<a href="{{path('cms_contactblock_index')}}">
							<span class="sub-item">{% trans %}Contact{% endtrans %}</span>
						</a>
					</li>
					<li>
						<a href="{{path('cms_imagevideo_index')}}">
							<span class="sub-item">{% trans %}Images&Video{% endtrans %}</span>
						</a>
					</li>
					<li>
						<a href="{{path('cms_header_index')}}">
							<span class="sub-item">{% trans %}Header{% endtrans %}</span>
						</a>
					</li>
					<li>
						<a href="{{path('cms_feature_index')}}">
							<span class="sub-item">{% trans %}Feature{% endtrans %}</span>
						</a>
					</li>
					<li>
						<a href="{{path('cms_team_membre_index')}}">
							<span class="sub-item">{% trans %}Team & membres{% endtrans %}</span>
						</a>
					</li>
					<li>
						<a href="{{path('cms_pricing_index')}}">
							<span class="sub-item">{% trans %}Pricing{% endtrans %}</span>
						</a>
					</li>
					<li>
						<a href="{{path('cms_pageservice_index')}}">
							<span class="sub-item">{% trans %}Page Services{% endtrans %}</span>
						</a>
					</li>

				</ul>
			</div>
				</li>
				{% endblock %}
{% block blog %}
				<li class="nav-item">

				<a data-toggle="collapse" href="#blog">
				<i class="fas fa-user-cog"></i>
				<p>{% trans %}User Blog{% endtrans %}</p>
				<span class="caret"></span>
				</a>
				<div class="collapse" id="blog">
				<ul class="nav nav-collapse">
					<li>
						<a href="{{path('cms_list_categories')}}">
							<span class="sub-item">{% trans %}Categories{% endtrans %}</span>
						</a>
					</li>
					<li>
						<a href="{{path('cms_list_articles')}}">
							<span class="sub-item">{% trans %}Posts{% endtrans %}</span>
						</a>
					</li>
					<li>
						<a href="{{path('cms_list_tags')}}">
							<span class="sub-item">{% trans %}Tags{% endtrans %}</span>
						</a>
					</li>
					
					

				</ul>
			</div>
				</li>
				{% endblock %}
				{% block news %}
				<li class="nav-item">

				<a href="{{path('cms_news_index')}}">
				<i class="far fa-newspaper"></i>
				<p>{% trans %}News{% endtrans %}</p>
				<span class="caret"></span>
				</a>
				</li>
				{% endblock %}
				 {% block forum %}
				<li class="nav-item">

				<a data-toggle="collapse" href="#forum">
				<i class="fas fa-cubes"></i>
				<p>{% trans %}User Forum{% endtrans %}</p>
				<span class="caret"></span>
				</a>
				<div class="collapse" id="forum">
				<ul class="nav nav-collapse">
					<li>
						<a href="{{path('cms_forum_index')}}">
							<span class="sub-item">{% trans %}Forums{% endtrans %}</span>
						</a>
					</li>
					<li>
						<a href="{{path('cms_topic_index')}}">
							<span class="sub-item">{% trans %}Topics{% endtrans %}</span>
						</a>
					</li>
					
					

				</ul>
			</div>
				</li>
				{% endblock %}
{% block content %}
<div class="container bootstrap snippet">
 {{ form_start(form) }} 
   
    <div class="row">
<!--/col-3-->
    	<div class="col-sm-12">
            

              
          <div class="tab-content">
            <div class="tab-pane active" id="home">
             
                <div class="card">
                <div class="card-header">
        <a href="#" class="btn btn-secondary btn-block">{% trans %}Add User Invit{% endtrans %}</a>
                      <div class="form-group">
                          
                          <div class="col-xs-7">
                         
                              <label for="first_name"><h4>{% trans %}User Recevier{% endtrans %}</h4></label>
                              {{ form_errors(form.receiverinvit) }}
                        {{ form_widget(form.receiverinvit, { 'attr': {'class': 'form-control form-group has-success'} }) }}  </div>
                      </div>
                     
           <div class="form-group">
                          
                          <div class="col-xs-7">
                         
                              <label for="first_name"><h4>{% trans %}Web Site{% endtrans %}</h4></label>
                              {{ form_errors(form.sites) }}
                        {{ form_widget(form.sites, { 'attr': {'class': 'form-control form-group has-success'} }) }}  </div>
                      </div>
                        <div class="form-group">
                          
                          <div class="col-xs-7">
                         
                              <label for="first_name"><h4>{% trans %}Role Attribuation{% endtrans %}</h4></label>
                              {{ form_errors(form.role) }}
                        {{ form_widget(form.role, { 'attr': {'class': 'form-control'} }) }}  </div>
                      </div>
                  
                      
                     
                    
                      <div class="form-group">
                           <div class="col-xs-12">
                                <br>
                                {{ form_rest(form) }}
													<button type="submit" value=""  class="btn btn-primary">{% trans %}Save{% endtrans %}</button>
                                                <button type="reset" value="" class="btn btn-danger">{% trans %}Reset{% endtrans %}</button>
                            </div>
                      </div>
              	</form>
              <hr>
               </div> </div>
             </div><!--/tab-pane-->
             <div class="tab-pane" id="messages">
               
               <h2></h2>
               
            
           
               
             </div><!--/tab-pane-->
       
               
              </div><!--/tab-pane-->
          </div><!--/tab-content-->

        </div>
        {{ form_end(form) }}<!--/col-9-->
    </div>
{% endblock %}
 {% block javascripts %}
 
 

<!-- jQuery UI -->
<script src="{{asset('assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js')}}"></script>

<!-- jQuery Scrollbar -->
<script src="{{asset('assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js')}}"></script>

<!-- Moment JS -->
<script src="{{asset('assets/js/plugin/moment/moment.min.js')}}"></script>

<!-- Chart JS -->
<script src="{{asset('assets/js/plugin/chart.js/chart.min.js')}}"></script>

<!-- jQuery Sparkline -->
<script src="{{asset('assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js')}}"></script>

<!-- Chart Circle -->
<script src="{{asset('assets/js/plugin/chart-circle/circles.min.js')}}"></script>

<!-- Datatables -->
<script src="{{asset('assets/js/plugin/datatables/datatables.min.js')}}"></script>

<!-- Bootstrap Notify -->
<script src="{{asset('assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js')}}"></script>

<!-- Bootstrap Toggle -->
<script src="{{asset('assets/js/plugin/bootstrap-toggle/bootstrap-toggle.min.js')}}"></script>

<!-- jQuery Vector Maps -->
<script src="{{asset('assets/js/plugin/jqvmap/jquery.vmap.min.js')}}"></script>
<script src="{{asset('assets/js/plugin/jqvmap/maps/jquery.vmap.world.js')}}"></script>

<!-- Google Maps Plugin -->
<script src="{{asset('assets/js/plugin/gmaps/gmaps.js')}}"></script>

<!-- Sweet Alert -->
<script src="{{asset('assets/js/plugin/sweetalert/sweetalert.min.js')}}"></script>

<!-- Azzara JS -->
<script src="{{asset('assets/js/ready.min.js')}}"></script>

<!-- Azzara DEMO methods, don't include it in your project! -->
<script src="{{asset('assets/js/setting-demo.js')}}"></script>
<script src="{{asset('assets/js/demo.js')}}"></script>
 <script>
		$('#displayNotif').on('load', function(){
			var placementFrom = $('#notify_placement_from option:selected').val();
			var placementAlign = $('#notify_placement_align option:selected').val();
			var state = $('#notify_state option:selected').val();
			var style = $('#notify_style option:selected').val();
			var content = {};

			content.message = 'New Site has been added';
			content.title = 'Site notify';
			if (style == "withicon") {
				content.icon = 'fa fa-bell';
			} else {
				content.icon = 'none';
			}
			content.url = 'index.html';
			content.target = '_blank';

			$.notify(content,{
				type: state,
				placement: {
					from: placementFrom,
					align: placementAlign
				},
				time: 1000,
				delay: 0,
			});
		});
	</script>





<script>
$('select').select2();

</script>
 {% endblock %}